# Generated by Django 2.0.3 on 2019-04-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('owner', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField()),
                ('address', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='panel_icon')),
                ('title', models.CharField(default='', max_length=100)),
                ('video', models.FileField(blank=True, upload_to='videos')),
                ('weather_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_city', to='api.City', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='SlidingText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=500)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliding_texts', to='api.Panel')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.Panel'),
        ),
    ]
