# Generated by Django 2.0.3 on 2019-05-13 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('owner', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField()),
                ('address', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Trabzon', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('owner', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField()),
                ('address', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='panel_icon')),
                ('title', models.CharField(default='', max_length=100)),
                ('video', models.FileField(upload_to='videos', verbose_name='Video (mp4)')),
                ('timetable', models.FileField(blank=True, upload_to='files', verbose_name='Timetable (xlsx)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('weather_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_city', to='api.City', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='SlidingText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=500)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliding_texts', to='api.Panel')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.Panel'),
        ),
        migrations.AddField(
            model_name='activity',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.Panel'),
        ),
    ]
