# Generated by Django 2.0.3 on 2019-05-13 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='address',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='owner',
            new_name='professor',
        ),
        migrations.RemoveField(
            model_name='class',
            name='date',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='timetable',
        ),
        migrations.AddField(
            model_name='class',
            name='day',
            field=models.CharField(choices=[('Pazartesi', 'Pazartesi'), ('Salı', 'Salı'), ('Çarşamba', 'Çarşamba'), ('Perşembe', 'Perşembe'), ('Cuma', 'Cuma')], default='Pazartesi', max_length=10),
        ),
        migrations.AddField(
            model_name='class',
            name='end_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
