# Generated by Django 2.0.3 on 2019-04-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidingText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=500)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Panel')),
            ],
        ),
    ]
