# Generated by Django 2.0.3 on 2019-04-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_slidingtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidingtext',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliding_texts', to='api.Panel'),
        ),
    ]
