# Generated by Django 2.0.13 on 2019-05-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190513_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='classroom',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='professor',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='slidingtext',
            name='text',
            field=models.TextField(),
        ),
    ]
