# Generated by Django 2.0.13 on 2019-05-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190517_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='weather_city',
            field=models.CharField(choices=[('Trabzon', 'Trabzon'), ('İstanbul', 'İstanbul')], default='Trabzon', max_length=20),
        ),
    ]
