# Generated by Django 2.0.3 on 2019-04-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190418_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='icon',
            field=models.FileField(upload_to=''),
        ),
    ]
