# Generated by Django 2.0.3 on 2019-04-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190419_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='icon',
            field=models.ImageField(blank=True, upload_to='panel_icon'),
        ),
    ]
