# Generated by Django 2.0.3 on 2019-04-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190419_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='video',
            field=models.FileField(blank=True, upload_to='videos', verbose_name=''),
        ),
    ]
