# Generated by Django 2.0.3 on 2019-04-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_panel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='video',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
