# Generated by Django 2.0.3 on 2019-03-24 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20190324_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SlidingText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='main',
            name='sliding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.SlidingText'),
        ),
    ]
